import { useState } from 'react';
import { ARCHETYPES } from '../data/archetypes';
import { createPet } from '../game/simulation';
import { useWorldLighting } from '../hooks/useWorldLighting';
import type { PetArchetype, PetState } from '../types/pet';
import { Pet } from './Pet';
import { PetRoom } from './PetRoom';

function ArchetypePreview({ id }: { id: PetArchetype }) { const path = id === 'robot' ? 'M15 14h18v16H15z' : id === 'bird' ? 'm14 23 10-12 10 12-10 9Z' : id === 'rabbit' ? 'M19 15 17 4m12 11 2-11' : id === 'dragon' ? 'M12 24 5 16l10 2 9-9 9 9 10-2-7 8' : 'M12 25c0-10 7-15 12-15s12 5 12 15c-4 7-20 7-24 0Z'; return <svg viewBox="0 0 48 40" aria-hidden="true"><circle cx="24" cy="21" r="13" fill="currentColor" opacity=".22" /><path d={path} fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>; }

function Setup({ archetype, setArchetype, name, setName, onContinue, onCancel }: { archetype: PetArchetype; setArchetype: (value: PetArchetype) => void; name: string; setName: (value: string) => void; onContinue: () => void; onCancel?: () => void }) { return <section className="new-pal-card new-pal-card--setup"><div className="new-pal-heading"><span className="eyebrow">A new beginning</span><h1>Meet your next pal</h1><p>Choose a kind of creature. Their individual look and home will be a surprise.</p></div><fieldset className="archetype-picker"><legend>Choose an archetype</legend><div>{ARCHETYPES.map((item) => <button type="button" key={item.id} className={archetype === item.id ? 'is-selected' : ''} onClick={() => setArchetype(item.id)} aria-pressed={archetype === item.id}><ArchetypePreview id={item.id} /><span>{item.label}</span></button>)}</div></fieldset><form onSubmit={(event) => { event.preventDefault(); onContinue(); }}><label htmlFor="new-pal-name">What should we call them?</label><div className="name-input"><input id="new-pal-name" value={name} onChange={(event) => setName(event.target.value)} maxLength={18} placeholder="Mochi" autoFocus /><button type="submit">Reveal my pal <span aria-hidden="true">→</span></button></div></form>{onCancel && <button className="new-pal-cancel" onClick={onCancel}>Keep my current pal</button>}</section>; }

function Reveal({ candidate, onCandidateName, onAdopt, onReroll, onBack }: { candidate: PetState; onCandidateName: (name: string) => void; onAdopt: () => void; onReroll: () => void; onBack: () => void }) { const lighting = useWorldLighting(); return <section className="new-pal-card new-pal-card--reveal"><div className="preview-heading"><div><span className="eyebrow">A little reveal</span><h1>Say hello to {candidate.name}</h1><p>{candidate.archetype[0].toUpperCase() + candidate.archetype.slice(1)} · {candidate.habitat.archetype.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' ')}</p></div><label className="preview-name">Name<input value={candidate.name} onChange={(event) => onCandidateName(event.target.value)} maxLength={18} /></label></div><div className="preview-room"><PetRoom pet={candidate} lighting={lighting} /><Pet pet={candidate} /></div><div className="reveal-actions"><button className="reveal-secondary" onClick={onBack}>Back</button><button className="reveal-secondary" onClick={onReroll}>Reroll</button><button className="reveal-adopt" onClick={onAdopt}>Adopt {candidate.name} <span aria-hidden="true">→</span></button></div></section>; }

export function NewPalFlow({ onAdopt, onCancel }: { onAdopt: (candidate: PetState) => void; onCancel?: () => void }) { const [stage, setStage] = useState<'setup' | 'reveal'>('setup'); const [archetype, setArchetype] = useState<PetArchetype>('dog'); const [name, setName] = useState(''); const [candidate, setCandidate] = useState<PetState | null>(null); const continueToReveal = () => { const next = createPet(name, archetype); setCandidate(next); setStage('reveal'); }; const reroll = () => { const next = createPet(candidate?.name || name, archetype); setCandidate(next); }; return <main className={`new-pal-flow new-pal-flow--${stage}`}><div className="new-pal-backdrop" />{stage === 'setup' || !candidate ? <Setup archetype={archetype} setArchetype={setArchetype} name={name} setName={setName} onContinue={continueToReveal} onCancel={onCancel} /> : <Reveal candidate={candidate} onCandidateName={(nextName) => setCandidate({ ...candidate, name: nextName })} onAdopt={() => onAdopt(candidate)} onReroll={reroll} onBack={() => { setName(candidate.name); setCandidate(null); setStage('setup'); }} />}</main>; }
